# Generated by Django 4.1.2 on 2022-11-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionlisting_lister_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='stating_bid',
            new_name='starting_bid',
        ),
    ]
