# Generated by Django 4.1.2 on 2022-11-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction',
            new_name='product',
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='observing', to='auctions.auctionlisting')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
