# Generated by Django 4.1.2 on 2022-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.FloatField(null=True),
        ),
    ]
