# Generated by Django 4.1.2 on 2022-11-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auction_bid_product_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='observing', to='auctions.auctionlisting'),
        ),
    ]
