# Generated by Django 4.1.2 on 2022-12-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_categoryname_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
    ]
